version: "3"
services:
  php-service:
    container_name: php-lrv
    build: ./docker/php
    volumes:
      - ./:/var/www/html/
    ports:
      - 10001:80
      - 10004:5173
    networks:
      - www-lrv
  mysql-service:
    container_name: mysql-lrv
    build: ./docker/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database-lrv:/var/lib/mysql/
    networks:
      - www-lrv
    ports:
      - 10003:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - php-service
  phpmyadmin-service:
    container_name: phpmyadmin-lrv
    build: ./docker/phpmyadmin
    depends_on:
      - php-service
      - mysql-service
    restart: always
    ports:
      - "10002:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - www-lrv
volumes:
  database-lrv:
networks:
  www-lrv:
